package mx.itson.benito.ui;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.benito.entidades.Orden;
import mx.itson.benito.entidades.Pedido;
import mx.itson.benito.persistencia.OrdenDAO;
import mx.itson.benito.persistencia.PedidoDAO;

/**
 * Formulario para agregar o editar una orden
 *
 * @author lm
 */
public class FormularioOrden extends javax.swing.JDialog {

    private final java.awt.Frame parent;
    private final DefaultTableModel modelPedidosTbl;
    private final Orden orden;
    private List<Pedido> pedidos = new ArrayList<>();
    private Pedido pedido;

    public Pedido getPedido() {
        return pedido;
    }

    public void setPedido(Pedido o) {
        pedido = o;
    }

    /**
     * Creates new form FormularioOrden
     */
    public FormularioOrden(java.awt.Frame parent, boolean modal, Orden orden) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.orden = orden;

        modelPedidosTbl = (DefaultTableModel) tblPedidos.getModel();

        if (this.pedido != null) {
            llenarTabla(pedido);
        }

        if (this.orden != null) {
            pedidos = orden.getPedidos();
        }

        llenarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tfdFolio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfdFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfdComentario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnAgregarArticulo = new javax.swing.JButton();
        btnQuitarArticulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Orden");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Articulo", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPedidos);
        if (tblPedidos.getColumnModel().getColumnCount() > 0) {
            tblPedidos.getColumnModel().getColumn(0).setResizable(false);
            tblPedidos.getColumnModel().getColumn(1).setResizable(false);
            tblPedidos.getColumnModel().getColumn(1).setPreferredWidth(2);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, 170));

        jLabel2.setText("Articulos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        tfdFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFolioActionPerformed(evt);
            }
        });
        jPanel1.add(tfdFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 280, -1));

        jLabel3.setText("Folio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel1.add(tfdFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 280, -1));

        jLabel4.setText("Fecha:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));
        jPanel1.add(tfdComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 280, -1));

        jLabel5.setText("Comentario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        btnAgregarArticulo.setText("Agregar articulo");
        btnAgregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArticuloActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, -1));

        btnQuitarArticulo.setText("Quitar articulo");
        btnQuitarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarArticuloActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuitarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 240, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFolioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArticuloActionPerformed
        new AgregarArticuloOrden(parent, true, this).setVisible(true);

        pedidos.add(pedido);

        if (this.pedido != null) {
            llenarTabla(pedido);
        }
    }//GEN-LAST:event_btnAgregarArticuloActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

        try {
            
            if (this.orden != null) {
                OrdenDAO.editar(
                        orden.getId(), 
                        pedidos,
                        tfdComentario.getText(), 
                        formato.parse(tfdFecha.getText()), 
                        tfdFolio.getText()
                );
            }
            
            Orden o = new Orden();

            o.setTotal(0);
            o.setSubtotal(0);
            o.setComentario(tfdComentario.getText());
            o.setFecha(formato.parse(tfdFecha.getText()));
            o.setFolio(tfdFolio.getText());

            for (Pedido p : pedidos) {
                p.setOrden(o);
                PedidoDAO.guardar(p.getArticulo(), p.getOrden(), p.getCantidad());

                /*
                if (this.orden != null) {
                    OrdenDAO.editar(orden.getId(), pedidos, 0, 0, tfdComentario.getText(), formato.parse(tfdFecha.getText()), tfdFolio.getText());
                    //PedidoDAO.editar(p.getId(), p.getArticulo(), p.getOrden(), p.getCantidad());

                }
                */
            }

            this.dispose();

        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnQuitarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarArticuloActionPerformed
        try {
            int filaSeleccionada = tblPedidos.getSelectedRow();

            if (JOptionPane.showConfirmDialog(parent, "¿Quieres quitar este articulo?") == JOptionPane.YES_OPTION) {
                modelPedidosTbl.removeRow(filaSeleccionada);
                pedidos.remove(filaSeleccionada);
            }

        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btnQuitarArticuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioOrden dialog = new FormularioOrden(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     * Llena la tabla con los pedidos
     *
     * @param pedido El pedido
     */
    private void llenarTabla(Pedido pedido) {
        modelPedidosTbl.addRow(
                new Object[]{
                    pedido.getArticulo(),
                    pedido.getCantidad()
                }
        );
    }

    /**
     * Llena el formulario si se va a editar una orden
     */
    private void llenarFormulario() {
        if (this.orden != null) {
            tfdFolio.setText(orden.getFolio());
            tfdFecha.setText(orden.getFecha().toString());
            tfdComentario.setText(orden.getComentario());

            for (Pedido p : orden.getPedidos()) {
                llenarTabla(p);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregarArticulo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnQuitarArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField tfdComentario;
    private javax.swing.JTextField tfdFecha;
    private javax.swing.JTextField tfdFolio;
    // End of variables declaration//GEN-END:variables
}
